title:             Projects, Portfolio, & Posts
description:       All Things Programming...
author:            Russell Chapman
github_username:   chpmnrssll
paginate_path:     /page:num/
paginate:          6

collections:
  json:
    output: true
    permalink: /:collection/:path

sass:
  style:    compressed
  sass_dir: /assets/css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
