author:          Russell Chapman
description:     Program all the things...
github_username: chpmnrssll
host:            192.168.1.70
permalink:       /posts/:categories/:title
title:           Russell Chapman

sass:
  style:    compressed
  sass_dir: /assets/css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
