author: Russell Chapman
description: Program all the things...
# host: 192.168.1.64
baseurl: /jekyll
permalink: /posts/:categories/:title
title: Russell Chapman

github_username: chpmnrssll
github_repository: chpmnrssll.github.io
github_branch: master

disqus:
  shortname: https-chpmnrssll-github-io

sass:
  style: compressed
  sass_dir: /public/css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
