title: Projects, Portfolio, & Posts
description: All Things Programming...
author: Russell Chapman
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
sass:
  style: compressed
