title:             "Projects, Portfolio, & Posts"
description:       "All Things Programming..."
author:            "Russell Chapman"
github_username:   "chpmnrssll"
logo:              "logo"
banner-title:      "add banner title"
banner-desc:       "add banner description"
discus_identifier: "add your discus identifier"
analytics:         "add your analytics identifier"
permalink:         "/blog/:year/:month/:day/:title"
paginate_path:     "/page:num/"
paginate:          2

sass:
  style:    "compressed"
  sass_dir: "/assets/css"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"
  - "jekyll-avatar"
