title:           Projects, Portfolio, & Posts
description:     All Things Programming...
author:          Russell Chapman
github_username: chpmnrssll
permalink:       /:collection/:title
paginate_path:   /:num
paginate:        6

sass:
  style:    compressed
  sass_dir: /assets/css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
